locale: 
  file: locale.en
wands:
  manage: 280
  settings: 340
trader: 
  patterns:
    file: 'patterns.yml'
    default: ''
  inventory-navigation: 
    sell-tab: 
      item: '35:3'
    buy-tab: 
      item: '35:5'
    manage-price: 
      item: '35:15'
    manage-buy-limit: 
      item: '35:12'
    manage-global-limit: 
      item: '35:11'
    manage-player-limit:
      item: '35:12'
    return: 
      item: '35'
    amounts-return: 
      item: '35:14'
bank: 
  withdraw-fee: 0.0
  deposit-fee: 0.0
  tab-size: 5
  max-tabs: 9
  tab-prices: 
    tab2: 100.0
    tab3: 200.0
    tab4: 500.0
    tab5: 1000.0
    tab6: 2000.0
    tab7: 5000.0
    tab8: 10000.0
    tab9: 50000.0
  player-accounts:
    file: player_accounts.yml
  guild-accounts: 
    file: guild_accounts.yml
money-bank:
  exchange-item: 388
  item-value: 10.0   
logging: 
  general: 
    enable: true
  player-trader: 
    enable: true 
    file: player_trader_logs.yml
  