trader: 
  #allows to change how ofthen a player can open a trader (can be by passed)
  rclick-interval: 1000
  #locale settings
  locale:
    file: locale.eng
  #allows to change the item to toggle mm (stick is default)
  manager-mode-toggle: 280
  #management and inventory switch custom items
  inventory-navigation: 
    #the item which appear when in the "buy" tab
    sell-tab: '35:5'
    #the item which appear when in the "sell" tab
    buy-tab: '35:3'
    #Price management
    manage-price: '35:15'
    #Buy limit management (player trader [buy tab])
    manage-buy-limit: '35:12'
    #Global limit management (server trader)
    manage-global-limit: '35:11'
    #Player limit management (server trader and player trader [sell tab])
    manage-player-limit: '35:12'
    #managing-return item 
    return: 35
    #amounts selection return
    amounts-return: '35:14'
  bank:
    withdraw-fee: 0.0
    deposit-fee: 0.0
    max-tabs: 0.0
    player-accounts:
      file: player_accounts.yml
    guild-accounts: 
      file: guild_accounts.yml