locale: 
  file: locale.eng
wands:
  manage: 280
  settings: 386
trader: 
  inventory-navigation: 
    sell-tab: '35:5'
    buy-tab: '35:3'
    manage-price: '35:15'
    manage-buy-limit: '35:12'
    manage-global-limit: '35:11'
    manage-player-limit: '35:12'
    return: 35
    amounts-return: '35:14'
bank: 
  tab-size: 3
  withdraw-fee: 0.0
  deposit-fee: 0.0
  max-tabs: 9
  tab-prices: 
    tab2: 100.0
    tab3: 200.0
    tab4: 500.0
    tab5: 1000.0
    tab6: 2000.0
    tab7: 5000.0
    tab8: 10000.0
    tab9: 50000.0
  player-accounts:
    file: player_accounts.yml
  guild-accounts: 
    file: guild_accounts.yml
money-bank:
  exchange-item: 388
  item-value: 10.0   
logging:
  basedir: ''
  