locale: 
  file: english.loc
wands:
  manage: 280
  settings: 340
trader: 
  patterns:
    file: 'patterns.yml'
    default: ''
  prices-lore:
    player-inventory:
    - '^7Unit price: ^6{unit}'
    - '^7Stack price: ^6{stack}'
    - ^7Double click to sell
    trader-inventory:
    - '^7Price: ^6{price}'
    - ^7Click to buy
  inventory-navigation: 
    sell-tab:
      item: '35:5'
      name: '^rSell tab'
      lore: 
      - ^6Click to buy items
    buy-tab: 
      item: '35:3'
      name: '^rBuy tab'
      lore: 
      - ^6Click to see what items you can sell
    manage-price: 
      item: '35:15'
      name: '^rPrice managing'
      lore: 
      - ^6Manage prices for items
    manage-buy-limit: 
      item: '35:12'
      name: '^rBuy limit managing'
      lore: 
      - ^6Manage how many items you 
      - ^6want to buy from players
    manage-global-limit: 
      item: '35:11'
      name: '^rGlobal limit managing'
      lore: 
      - ^6Manage global limits
    manage-player-limit:
      item: '35:12'
      name: '^rPlayer limit managing'
      lore: 
      - ^6Manage player limits
    return: 
      item: '35'
      name: '^rReturn'
      lore: 
      - ^6Return to stock managing
    amounts-return: 
      item: '35:14'
      name: '^rReturn'
      lore: 
      - ^6Return to buy other items
bank: 
  tab-size: 3
  withdraw-fee: 0.0
  deposit-fee: 0.0
  max-tabs: 9
  tab-prices: 
    tab2: 100.0
    tab3: 200.0
    tab4: 500.0
    tab5: 1000.0
    tab6: 2000.0
    tab7: 5000.0
    tab8: 10000.0
    tab9: 50000.0
  player-accounts:
    file: player_accounts.yml
  guild-accounts: 
    file: guild_accounts.yml
money-bank:
  exchange-item: 388
  item-value: 10.0   
logging: 
  general: 
    enable: true
  player-trader: 
    enable: true 
    file: player_trader_logs.yml
  