name: DtlCitizensTrader
main: net.dtl.citizens.trader.CitizensTrader
depend: [Citizens,Vault]
soft-depend: [DtlPermissions,PexPermissions,GroupManager,Towny,SimpleClans,Denizen,bPermissions]
version: 2.0RC v0.5
description: >
             Citizens Character. 
commands: 
    trader:
      aliases: dtrader
      description: Dtl - CitizensTrader trader commands.
      usage: |
             Usage: 
             /<command> help
             /<command> create <name> [type] [wallet] [owner] [account] [entity]
             /<command> list <stock> [page]
             /<command> wallet [wallet] [account]
             /<command> type [type]
             /<command> manage <name>
             /<command> open
             /<command> owner [owner]
             /<command> log [trader name] 
             /<command> clearlog [trader name] 
             /<command> clear [stock]
             /<command> pattern [action] 
             /<command> pattern set (pattern)
             /<command> balance
             /<command> withdraw <amount>
             /<command> deposit <amount>
             /<command> reload
      permisison-message: You don't have "<permission>" permission, to use commands
    banker: 
      aliases: dbanker
      description: Dtl - CitizensTrader banker commands.
      usage: |
             Usage: 
             /<command> wallet [wallet]
             /<command> type [type]
             /<command> owner [owner]
             /<command> create <name> [type] [entity]
             /<command> reload
      permisison-message: You don't have "<permission>" permission, to use commands
permissions: 
  dtl.trader.*:
    default: op
    children:
      dtl.trader.options.*: true
      dtl.trader.types.*: true
      dtl.trader.wallets.*: true
      dtl.trader.managing.*: true
      dtl.trader.commands.*: true
      dtl.trader.bypass.*: true
  dtl.trader.options.*:
    default: true
    children:
      dtl.trader.options.sell: true
      dtl.trader.options.sell-amounts: true
      dtl.trader.options.buy: true
      dtl.trader.options.market: true
      dtl.trader.options.manage: false
  dtl.trader.types.*:
    default: true
    children: 
      dtl.trader.types.player: true
      dtl.trader.types.server: true
      dtl.trader.types.market: true
      dtl.trader.types.enchant: true
  dtl.trader.wallets.*:
    default: op
    children: 
      dtl.trader.wallets.npc: true
      dtl.trader.wallets.owner: true
      dtl.trader.wallets.bank: true
      dtl.trader.wallets.infinite: true
      dtl.trader.wallets.towny: true
      dtl.trader.wallets.simple-clans: true
  dtl.trader.managing.*: 
    default: op
    children: 
      dtl.trader.managing.prices: true
      dtl.trader.managing.global-limits: true
      dtl.trader.managing.player-limits: true
      dtl.trader.managing.buy-limits: true
      dtl.trader.managing.stack-price: true
      dtl.trader.managing.multiple-amounts: true
  dtl.trader.commands.*:
    default: op
    children:
      dtl.trader.commands.create: true
      dtl.trader.commands.list: true
      dtl.trader.commands.wallet: true
      dtl.trader.commands.type: true
      dtl.trader.commands.owner: true
      dtl.trader.commands.log: true
      dtl.trader.commands.clearlog: true
      dtl.trader.commands.balance: true
      dtl.trader.commands.withdraw: true
      dtl.trader.commands.deposit: true
      dtl.trader.commands.pattern: true
      dtl.trader.commands.patternreload: true
      dtl.trader.commands.clear: true
      dtl.trader.commands.manage: true
  dtl.trader.bypass.*:
    default: op
    children: 
      dtl.trader.bypass.creative: true
      dtl.trader.bypass.managing: true
      dtl.trader.bypass.market: true
      dtl.trader.bypass.drop-managing: true
  dtl.banker.*:
    default: op
    children: 
      dtl.banker.options.*: true
      dtl.banker.types.*: true
      dtl.banker.commands.*: true
      dtl.banker.managing.*: true
      dtl.banker.settings.*: true
      dtl.banker.bypass.*: true
  dtl.banker.bypass.*: 
    default: op
    children: 
      dtl.banker.bypass.creative: true
      dtl.banker.bypass.managing: true
  dtl.banker.options.*:
    default: op
    children: 
      dtl.banker.options.settings: true
      dtl.banker.options.account: true
      dtl.banker.options.manage: false
      dtl.banker.options.remote-banking: false
  dtl.banker.types.*:
    default: op
    children:
      dtl.banker.types.player-bank: true
      dtl.banker.types.guild-bank: true
      dtl.banker.types.money-bank: true
  dtl.banker.managing.*: 
    default: op
    children: 
      dtl.banker.managing.withdraw-fee: true
      dtl.banker.managing.deposit-fee: true
      dtl.banker.managing.settings-enabled: true
      dtl.banker.managing.tab-buying: true
  dtl.banker.settings.*:
    default: op
    children: 
      dtl.banker.settings.tab-item: true
      dtl.banker.settings.tab-buy: true
      dtl.banker.settings.tab-resize: true
  dtl.banker.commands.*:
    default: op
    children: 
      dtl.banker.commands.fee: true
      dtl.banker.commands.settings: true
      dtl.banker.commands.tab-buying: true
      dtl.banker.commands.tab-resize: true
      dtl.banker.commands.tab-item: true
      dtl.banker.commands.tab-name: true
      dtl.banker.commands.remote: true
      dtl.banker.commands.remote-admin: true
      
      
      
      
      
      
      