name: DtlCitizensTrader
main: net.dtl.citizenstrader.CitizensTrader
depend: [Citizens,Vault]
version: 1.0Beta
description: >
             Citizens Character.
commands: 
    trader:
      description: Dtl - CitizensTrader commands.
      usage: /trader [buy/sell] [list/add/remove/edit] (iIndex) (iID) (cost) (amout)
      permission: dtl.characters.trader
      permisison-message: You don't have <permission>
    